server:
  port: 8551
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mingmingzhixiao/polymerization.git       # 配置git仓库的地址
          search-paths: classpath:/polymerization                          # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: mingmingzhixiao                                          # git仓库的账号
          password: Wu123456                                         # git仓库的密码